language: php
php:
- 5.5
before_script:
  - travis_retry composer self-update && composer --version
  - composer install --prefer-source --optimize-autoloader
  - chmod 755 ./pharmacist.sh
script:
  ./pharmacist.sh

